GET http://localhost:3000/direct/{{$dotenv URL}}
destination-name: SAP_GATEWAY

###
POST http://localhost:3000/direct/{{$dotenv URL}}
destination-name: SAP_GATEWAY

###
GET http://localhost:3000/xsuaa/{{$dotenv URL}}
destination-name: SAP_GATEWAY
Authorization: Bearer {{$dotenv TOKEN}}

###
POST http://localhost:3000/xsuaa/{{$dotenv URL}}
destination-name: SAP_GATEWAY
Authorization: Bearer {{$dotenv TOKEN}}
###
POST http://localhost:3000/token
Content-Type: application/json

{
    "username": "{{$dotenv USERNAME}}",
    "password": "{{$dotenv PASSWORD}}"
}